### ISSUE TITLE
Defaulting to 'utf-8' encoding breaks pymlconf on Python 2

### ISSUE THREAD

**Issue by DonnchaC** [pylover/pymlconf#21]
Python 2 does not have support for open() with encoding='utf-8. I'm using a package with depends on pymlconf on Python 2 and this change has broken my tests. Let me know if you need any more information to debug this.

```
.tox/py27/lib/python2.7/site-packages/pymlconf/config_manager.py:76: in __init__
    self.load_files(files)
.tox/py27/lib/python2.7/site-packages/pymlconf/config_manager.py:109: in load_files
    loaded_yaml = load_yaml(f, self.context, encoding=self.encoding)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

file_path = '/home/ubuntu/<SNIP>'
macros = {}, encoding = 'utf-8'

    def load_yaml(file_path, macros=None, encoding='utf-8'):
>       stream = open(file_path, encoding=encoding)
E       TypeError: 'encoding' is an invalid keyword argument for this function

.tox/py27/lib/python2.7/site-packages/pymlconf/yaml_helper.py:29: TypeError
```

**Comment by pylover** [comment]
Yes of course. I'll fix it
On Aug 7, 2016 11:55 PM, DonnchaC <notifications@github.com> wrote:Python 2 does not have support for open() with encoding='utf-8. I'm using a package with depends on pymlconf on Python 2 and this change has broken my tests. Let me know if you need any more information to debug this.

.tox/py27/lib/python2.7/site-packages/pymlconf/config_manager.py:76: in __init__
    self.load_files(files)
.tox/py27/lib/python2.7/site-packages/pymlconf/config_manager.py:109: in load_files
    loaded_yaml = load_yaml(f, self.context, encoding=self.encoding)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

file_path = '/home/ubuntu/<SNIP>'
macros = {}, encoding = 'utf-8'

    def load_yaml(file_path, macros=None, encoding='utf-8'):
>       stream = open(file_path, encoding=encoding)
E       TypeError: 'encoding' is an invalid keyword argument for this function

.tox/py27/lib/python2.7/site-packages/pymlconf/yaml_helper.py:29: TypeError

**Comment by pylover** [comment]
Waiting for `compat.py` version

**Comment by pylover** [comment]
Closing after pypi

**Comment by pylover** [comment]
Version 0.5.1 uploaded on pypi: https://pypi.python.org/pypi/pymlconf
